name: focus
description: A new Flutter project.

publish_to: "none"

version: 1.1.3+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_bottom_bar: ^1.2.0
  cupertino_icons: ^1.0.3
  date_format: ^2.0.4
  flutter_local_notifications: ^9.0.0
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  hive: ^2.0.4
  intl: ^0.17.0
  lottie: ^1.2.1
  path_provider: ^2.0.4
  timezone: ^0.8.0
  equatable: ^2.0.3
  audioplayers: ^0.20.1
  flare_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/audios/
    - assets/
